name: markdown check
on:
  pull_request:
    branches:
      - main
      - dev
      - feature*
  push:
    branches:
      - check
jobs:
  markdown_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Check markdown format
        uses: avto-dev/markdown-lint@v1.5.0
        with:
          config: ".markdownlint.json"
          args: "**/*.md"
      - name: Check markdown link
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.13
        with:
          use-quiet-mode: "yes"
          folder-path: "./"
          config-file: '.github/config/markdownlink.json'
