name: markdown check
on:
  push:
    branches:
      - main
      - dev
jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Check markdown format
        uses: avto-dev/markdown-lint@v1.5.0
        with:
          config: ".markdownlint.json"
          args: "**/*.md"
